version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/node:16.14.2
        environment:
          UMB_PROJECT_ALIAS: $UMB_PROJECT_ALIAS
          UMB_API_KEY: $UMB_API_KEY
          PERCY_TOKEN: $PERCY_TOKEN
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn package cache
          key: v1-cache-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save yarn package cache
          paths:
            - ~/.cache/yarn
          key: v1-cache-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn percy:cypress
      - run:
          name: Build
          command: yarn build
